# Generated by Django 5.2.8 on 2025-11-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
